<?php
use Magento\Framework\App\Action\Action;
/**
 * @var $block \DaoNguyen\ProductsSlider\Block\ProductsSlider
 */
$collection1 = $block->getProductCollectionByCategory((int) $block->getCategoryId1());
$collection2 = $block->getProductCollectionByCategory((int) $block->getCategoryId2());
$image = 'product_page_main_image';
$type = 'widget-new-grid';
?>

<div class="block-products-slider">
    <div class="block-title">
        <p role="heading" aria-level="2"><?= $block->escapeHtml($block->getTitle()) ?></p>
    </div>
    <div class="block-content product data items">
        <div class="item title" data-role="collapsible" data-toggle="trigger">
            <a class="switch" href="#tab1">קטגוריה</a>
        </div>
        <div id="tab1" class="products item content" data-role="content">
            <ol id="slide-items-1" style="display: none;">
                <?php foreach ($collection1->getItems() as $item): ?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($item, $image)->toHtml() ?>
                            </a>
                            <?php $postParams = $block->getAddToCartPostParams($item); ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <form data-role="tocart-form"
                                            data-product-sku="<?= $escaper->escapeHtml($item->getSku()) ?>"
                                            action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                            data-mage-init='{"catalogAddToCart": {}}'
                                            method="post">
                                            <input type="hidden"
                                                name="product"
                                                value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                value="<?=
                                                /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    disabled>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($item->getName()) ?>
                                </a>
                            </strong>
                            <?= $block->getProductPriceHtml($item, $type); ?>

                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <div class="item title" data-role="collapsible" data-toggle="trigger">
            <a class="switch" href="#tab2">קטגוריה</a>
        </div>
        <div id="tab2" class="products item content" data-role="content">
            <ol id="slide-items-2" style="display: none;">
                <?php foreach ($collection2->getItems() as $item): ?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($item, $image)->toHtml() ?>
                            </a>
                            <?php $postParams = $block->getAddToCartPostParams($item); ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <form data-role="tocart-form"
                                            data-product-sku="<?= $escaper->escapeHtml($item->getSku()) ?>"
                                            action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                            data-mage-init='{"catalogAddToCart": {}}'
                                            method="post">
                                            <input type="hidden"
                                                name="product"
                                                value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                value="<?=
                                                /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    disabled>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($item->getName()) ?>
                                </a>
                            </strong>
                            <?= $block->getProductPriceHtml($item, $type); ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'slick',
        'tabs'
    ], function($) {
        $(function() {
            $(".block-content").on("dimensionsChanged", function (event, data) {
                var opened = data.opened;
                if (opened) {
                    $(event.target).next().children().first().slick('refresh');
                    return;
                }
            })

            $('#slide-items-2').on('init', function(event, slick) {
                $('#slide-items-2').show();
                $('.block-content').tabs({
                    active: 0,
                    openedState: "active"
                });
            });


            $('#slide-items-1').on('init', function(event, slick) {
                $('#slide-items-1').show();
                $('#slide-items-2').slick({
                    infinite: true,
                    speed: 300,
                    slidesToShow: 4,
                    slidesToScroll: 1,
                    rtl: true,
                    responsive: [
                        {
                            breakpoint: 768,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 1
                            }
                        }
                    ]
                });
            });

            $('#slide-items-1').slick({
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 1,
                rtl: true,
                responsive: [
                    {
                        breakpoint: 768,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    }
                ]
            })
        })
    })
</script>
