<?php
/**
 * @var $block \DaoNguyen\ProductsSlider\Block\ProductsSlider
 */
$collection1 = $block->getProductCollectionByCategory((int) $block->getCategoryId1());
$collection2 = $block->getProductCollectionByCategory((int) $block->getCategoryId2());
$image = 'product_page_main_image';
$type = 'widget-new-grid';
?>

<div class="block-products-slider">
    <div class="block-title">
        <p role="heading" aria-level="2"><?= $block->escapeHtml($block->getTitle()) ?></p>
    </div>
    <div class="block-content">
        <div id="tab1" class="products">
            <ol class="slide-items">
                <?php foreach ($collection1->getItems() as $item): ?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($item, $image)->toHtml() ?>
                            </a>
                        </div>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($item->getName()) ?>
                                </a>
                            </strong>
                            <?= $block->getProductPriceHtml($item, $type); ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
        <div id="tab2" class="products">
            <ol class="slide-items">
                <?php foreach ($collection2->getItems() as $item): ?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($item, $image)->toHtml() ?>
                            </a>
                        </div>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($item->getName()) ?>
                                </a>
                            </strong>
                            <?= $block->getProductPriceHtml($item, $type); ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function($) {
        $(function() {
            $('.slide-items').slick({
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 1
            })
        })
    })
</script>
